# Generated by Django 6.0 on 2025-12-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reportecdp_transaccioncdp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cruce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_realizado', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionCruce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, default='', max_length=100)),
                ('seller', models.CharField(blank=True, default='', max_length=100)),
                ('estado_vtex', models.CharField(blank=True, default='', max_length=100)),
                ('estado_payway', models.CharField(blank=True, default='', max_length=100)),
                ('estado_cdp', models.CharField(blank=True, default='', max_length=100)),
                ('estado_janis', models.CharField(blank=True, default='', max_length=100)),
                ('cruce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.cruce')),
            ],
        ),
    ]
