# Generated by Django 6.0 on 2025-12-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cruce_transaccioncruce'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncruce',
            name='estado_payway_2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
