# Generated by Django 4.2.27 on 2026-01-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_usuario_janis'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruce',
            name='revisar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reportevtex',
            name='filtros',
            field=models.JSONField(blank=True, help_text='Filtros utilizados para generar el reporte (ej: estados, métodos de pago)', null=True, verbose_name='Filtros aplicados'),
        ),
        migrations.AddField(
            model_name='transaccionvtex',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor del pedido'),
        ),
    ]
