# Generated by Django 4.2.27 on 2026-01-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_vtex_filtros_y_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFiltroVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código interno del filtro (ej: 'estado', 'metodo_pago')", max_length=50, unique=True)),
                ('nombre', models.CharField(help_text="Nombre legible del filtro (ej: 'Estado del pedido')", max_length=100)),
                ('parametro_api', models.CharField(help_text="Parámetro que usa la API de VTEX (ej: 'f_status', 'f_paymentNames')", max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparece como opción en el formulario')),
            ],
            options={
                'verbose_name': 'Tipo de Filtro VTEX',
                'verbose_name_plural': 'Tipos de Filtros VTEX',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='reportevtex',
            options={'verbose_name': 'Reporte VTEX', 'verbose_name_plural': 'Reportes VTEX'},
        ),
        migrations.AlterField(
            model_name='reportevtex',
            name='filtros',
            field=models.JSONField(blank=True, help_text='DEPRECATED: Usar filtros_aplicados', null=True, verbose_name='Filtros aplicados (LEGACY)'),
        ),
        migrations.CreateModel(
            name='ValorFiltroVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Código que usa la API de VTEX (ej: 'invoiced', 'payment-pending')", max_length=100)),
                ('nombre', models.CharField(help_text="Nombre legible del valor (ej: 'Facturado', 'Pago Pendiente')", max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparece como opción en el formulario')),
                ('tipo_filtro', models.ForeignKey(help_text='Tipo de filtro al que pertenece este valor', on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='core.tipofiltrovtex')),
            ],
            options={
                'verbose_name': 'Valor de Filtro VTEX',
                'verbose_name_plural': 'Valores de Filtros VTEX',
                'ordering': ['tipo_filtro', 'nombre'],
                'unique_together': {('tipo_filtro', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='FiltroReporteVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.ForeignKey(help_text='Reporte al que se aplica este filtro', on_delete=django.db.models.deletion.CASCADE, related_name='filtros_aplicados', to='core.reportevtex')),
                ('tipo_filtro', models.ForeignKey(help_text='Tipo de filtro aplicado', on_delete=django.db.models.deletion.CASCADE, related_name='filtros_reportes', to='core.tipofiltrovtex')),
                ('valor_filtro', models.ForeignKey(help_text='Valor del filtro aplicado', on_delete=django.db.models.deletion.CASCADE, related_name='filtros_reportes', to='core.valorfiltrovtex')),
            ],
            options={
                'verbose_name': 'Filtro de Reporte VTEX',
                'verbose_name_plural': 'Filtros de Reportes VTEX',
                'unique_together': {('reporte', 'tipo_filtro', 'valor_filtro')},
            },
        ),
    ]
