# Generated by Django 4.2.27 on 2026-01-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_incluir_sellers_to_reportevtex'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccioncruce',
            name='monto_payway',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccioncruce',
            name='monto_payway_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccioncruce',
            name='valor_vtex',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
