# Generated by Django 4.2.27 on 2026-02-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tareacatalogacion_usuariocarrefourweb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('app_key', models.CharField(max_length=200, verbose_name='API App Key')),
                ('app_token', models.CharField(max_length=500, verbose_name='API App Token')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
            ],
            options={
                'verbose_name': 'Seller VTEX',
                'verbose_name_plural': 'Sellers VTEX',
            },
        ),
        migrations.AlterField(
            model_name='tareacatalogacion',
            name='tipo',
            field=models.CharField(choices=[('BUSQUEDA_EANS', 'Busqueda EANs'), ('BUSQUEDA_CATEGORIAS', 'Busqueda Categorias'), ('SELLERS_EXTERNOS', 'Sellers Externos'), ('SELLERS_NO_CARREFOUR', 'Sellers No Carrefour'), ('ACTUALIZAR_MODAL', 'Actualizar Modal'), ('CONSULTA_VISIBILIDAD', 'Consulta Visibilidad')], max_length=30),
        ),
        migrations.CreateModel(
            name='SkuVtex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuId', models.CharField(max_length=200, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='core.productovtex')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaVisibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField()),
                ('motivo', models.CharField(blank=True, default='', max_length=300)),
                ('stock', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiene_imagenes', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_visibilidad', to='core.sellervtex')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_visibilidad', to='core.skuvtex')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_visibilidad', to='core.tareacatalogacion')),
            ],
        ),
    ]
