# Generated by Django 4.2.27 on 2026-02-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productovtex_sellervtex_alter_tareacatalogacion_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellervtex',
            name='marketplace',
            field=models.ForeignKey(blank=True, help_text='Seller madre/marketplace. Dejar vacio si este seller ES el marketplace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='core.sellervtex', verbose_name='Marketplace madre'),
        ),
    ]
