# Generated by Django 4.2.27 on 2026-02-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sellervtex_marketplace_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareacatalogacion',
            name='tipo',
            field=models.CharField(choices=[('BUSQUEDA_EANS', 'Busqueda EANs'), ('BUSQUEDA_CATEGORIAS', 'Busqueda Categorias'), ('SELLERS_EXTERNOS', 'Sellers Externos'), ('SELLERS_NO_CARREFOUR', 'Sellers No Carrefour'), ('ACTUALIZAR_MODAL', 'Actualizar Modal'), ('CONSULTA_VISIBILIDAD', 'Consulta Visibilidad'), ('EXPORT_CATALOGO', 'Export Catalogo')], max_length=30),
        ),
    ]
