# Generated by Django 4.2.27 on 2026-03-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_tareacatalogacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerExterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_sincronizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller Externo',
                'verbose_name_plural': 'Sellers Externos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='tareacatalogacion',
            name='tipo',
            field=models.CharField(choices=[('BUSQUEDA_EANS', 'Busqueda EANs'), ('BUSQUEDA_CATEGORIAS', 'Busqueda Categorias'), ('SELLERS_EXTERNOS', 'Sellers Externos'), ('SELLERS_NO_CARREFOUR', 'Sellers No Carrefour'), ('ACTUALIZAR_MODAL', 'Actualizar Modal'), ('CONSULTA_VISIBILIDAD', 'Consulta Visibilidad'), ('EXPORT_CATALOGO', 'Export Catalogo'), ('CARGA_STOCK', 'Carga Stock'), ('EXPORT_MARKETPLACE', 'Export Marketplace')], max_length=30),
        ),
    ]
