# Generated by Django 4.2.27 on 2026-03-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sellerexterno_alter_tareacatalogacion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMercadoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='transaccioncruce',
            name='estado_mercado_pago',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccioncruce',
            name='monto_mercado_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaccionvtex',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor facturado'),
        ),
        migrations.CreateModel(
            name='TransaccionMercadoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=100)),
                ('id_operacion_mercado_pago', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_operacion', models.CharField(max_length=100)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.reportemercadopago')),
            ],
        ),
        migrations.AddField(
            model_name='cruce',
            name='reporte_mercado_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruces', to='core.reportemercadopago', verbose_name='Reporte MercadoPago'),
        ),
    ]
