# Generated by Django 4.2.27 on 2026-03-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_reportemercadopago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteBUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='transaccioncruce',
            name='estado_bus',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transaccioncruce',
            name='monto_bus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='TransaccionBUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(max_length=100)),
                ('tipo_pedido', models.CharField(max_length=20)),
                ('tipo_comprobante', models.CharField(blank=True, default='', max_length=100)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_recepcion_datos', models.CharField(blank=True, default='', max_length=100)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='core.reportebus')),
            ],
        ),
        migrations.AddField(
            model_name='cruce',
            name='reporte_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruces', to='core.reportebus', verbose_name='Reporte BUS'),
        ),
    ]
